AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Notes API using Lambda, API Gateway, and DynamoDB

Globals:
  Function:
    Timeout: 10
    Runtime: python3.14

Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Notes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  CreateNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Notes
      Environment:
        Variables:
          TABLE_NAME: Notes
      Events:
        CreateNoteApi:
          Type: Api
          Properties:
            Path: /notes
            Method: post

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/notes"